<?xml version="1.0" encoding="utf-8"?><Database Name="MotoMensajeria" Class="DCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-RR1BBOV\SQLEXPRESS;Initial Catalog=MotoMensajeria;User ID=AlejoDB" SettingsObjectName="CapaDatos.Properties.Settings" SettingsPropertyName="MotoMensajeriaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Envio" Member="eEnvio">
    <Type Name="eEnvio">
      <Column Name="idEnvio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nombreCliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="apellidoCliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="numCelCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="domicEntrega" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="localidadEntrega" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="unidades" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fragil" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="precioViaje" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="precioFinal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="FKMotoquero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Motoquero_Envio" Member="eMotoquero" ThisKey="FKMotoquero" OtherKey="id" Type="eMotoquero" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Motoquero" Member="eMotoquero">
    <Type Name="eMotoquero">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="numCelular" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="modeloMoto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Motoquero_Envio" Member="eEnvio" ThisKey="id" OtherKey="FKMotoquero" Type="eEnvio" />
    </Type>
  </Table>
</Database>